#ifndef __407_HW_CONFIG_H
#define __407_HW_CONFIG_H

#include "f407_gpio.h" /* GPIO_Pin_x + GPIOA/B 原语，其余枚举值在 Enroll.c 展开时由 Enroll_Internal.h 提供 */

/*
 * 407_hw_config.h 板级硬件映射宏
 */

/*
LED1=PC11  LED2=PC13  LED3=PB2
*/
/* LED 板级映射：LED1=PC11，LED2=PC13，LED3=PB2 ,Buzzer1=PC5 */
#define HW_LED_MAP(X) \
	X(LED1, GPIOC, GPIO_Pin_11) \
	X(LED2, GPIOC, GPIO_Pin_13) \
	X(LED3, GPIOB, GPIO_Pin_2) \
	X(Buzzer1, GPIOC, GPIO_Pin_5)

/* KEY 板级映射：KEY1=PE3，KEY2=PE5 */
#define HW_KEY_MAP(X) \
	X(KEY1, GPIOE, GPIO_Pin_3) \
	X(KEY2, GPIOE, GPIO_Pin_5) 

/* USART1 引脚定义：TX=PB6，RX=PB7（JY61P 姿态模块，AF7 复用） */
#define HW_USART1_TX_PORT GPIOB
#define HW_USART1_TX_PIN  GPIO_Pin_6
#define HW_USART1_RX_PORT GPIOB
#define HW_USART1_RX_PIN  GPIO_Pin_7

/* 无线串口 USART3 引脚定义：TX=PD8，RX=PD9 */
#define HW_USART3_TX_PORT GPIOD
#define HW_USART3_TX_PIN  GPIO_Pin_8
#define HW_USART3_RX_PORT GPIOD
#define HW_USART3_RX_PIN  GPIO_Pin_9

/* UART5 引脚定义：TX=PC12，RX=PD2（SU-03T 离线语音模块） */
#define HW_UART5_TX_PORT GPIOC
#define HW_UART5_TX_PIN  GPIO_Pin_12
#define HW_UART5_RX_PORT GPIOD
#define HW_UART5_RX_PIN  GPIO_Pin_2

/* UART4 引脚定义：TX=A0(PA0)，RX=A1(PA1)（F407 UART4 备用映射 AF8，调试口） */
#define HW_UART4_TX_PORT GPIOA
#define HW_UART4_TX_PIN  GPIO_Pin_0
#define HW_UART4_RX_PORT GPIOA
#define HW_UART4_RX_PIN  GPIO_Pin_1

/* USART 板级映射：JY61P 在 USART1，调试打印在 USART3，SU-03T 语音在 UART5，UART4 调试口 */
#define HW_USART_MAP(X) \
	X(API_USART1, API_USART_CORE_USART1, HW_USART1_TX_PORT, HW_USART1_TX_PIN, HW_USART1_RX_PORT, HW_USART1_RX_PIN) \
	X(API_USART3, API_USART_CORE_USART3, HW_USART3_TX_PORT, HW_USART3_TX_PIN, HW_USART3_RX_PORT, HW_USART3_RX_PIN) \
	X(API_USART4, API_USART_CORE_UART4,  HW_UART4_TX_PORT, HW_UART4_TX_PIN, HW_UART4_RX_PORT, HW_UART4_RX_PIN) \
	X(API_USART5, API_USART_CORE_UART5,  HW_UART5_TX_PORT, HW_UART5_TX_PIN, HW_UART5_RX_PORT, HW_UART5_RX_PIN)

/* TIM 板级映射：逻辑 API_TIM1 绑定到硬件 TIM3。 */
#define HW_TIM_MAP(X) \
	X(API_TIM1, API_TIM_CORE_TIM3) \
	X(API_TIM2, API_TIM_CORE_TIM2) \
	X(API_TIM3, API_TIM_CORE_TIM5)
	
/* PWM 板级映射：PE9 -> TIM1_CH1，PE11 -> TIM1_CH2，PE13 -> TIM1_CH3，PE14 -> TIM1_CH4 */
#define HW_PWM_MAP(X) \
	X(API_PWM_TIM1, API_PWM_CH1, API_PWM_CORE_TIM1, API_PWM_CORE_CH1, GPIOE, GPIO_Pin_9) \
	X(API_PWM_TIM1, API_PWM_CH2, API_PWM_CORE_TIM1, API_PWM_CORE_CH2, GPIOE, GPIO_Pin_11) \
	X(API_PWM_TIM1, API_PWM_CH3, API_PWM_CORE_TIM1, API_PWM_CORE_CH3, GPIOE, GPIO_Pin_13) \
	X(API_PWM_TIM1, API_PWM_CH4, API_PWM_CORE_TIM1, API_PWM_CORE_CH4, GPIOE, GPIO_Pin_14)

/* ADC 板级映射 */
/* ADC 板级映射：采样口在 PB1（ADC1 通道 9） */
#define HW_ADC_MAP(X) \
	X(API_ADC1, API_ADC_CH9, GPIOB, GPIO_Pin_1)

/* 软件 I2C1 引脚定义：SCL=PB8，SDA=PB9（MPU/QMC/BMP）*/
#define HW_I2C1_SCL_PORT GPIOB
#define HW_I2C1_SCL_PIN  GPIO_Pin_8
#define HW_I2C1_SDA_PORT GPIOB
#define HW_I2C1_SDA_PIN  GPIO_Pin_9

/* 软件 I2C2 引脚定义：SCL=PA7，SDA=PA5（OLED）*/
#define HW_I2C2_SCL_PORT GPIOA
#define HW_I2C2_SCL_PIN  GPIO_Pin_7
#define HW_I2C2_SDA_PORT GPIOA
#define HW_I2C2_SDA_PIN  GPIO_Pin_5

/* 软件 I2C3 引脚定义：SCL=PC2，SDA=PC0（PCA9685 #1）*/
#define HW_I2C3_SCL_PORT GPIOC
#define HW_I2C3_SCL_PIN  GPIO_Pin_2
#define HW_I2C3_SDA_PORT GPIOC
#define HW_I2C3_SDA_PIN  GPIO_Pin_0

/* 软件 I2C4 引脚定义：SCL=PB0，SDA=PC4（PCA9685 #2）*/
#define HW_I2C4_SCL_PORT GPIOB
#define HW_I2C4_SCL_PIN  GPIO_Pin_0
#define HW_I2C4_SDA_PORT GPIOC
#define HW_I2C4_SDA_PIN  GPIO_Pin_4

/* I2C 板级映射：I2C1=传感器，I2C2=OLED，I2C3=PCA9685#1，I2C4=PCA9685#2 */
#define HW_I2C_MAP(X) \
	X(API_I2C1, HW_I2C1_SCL_PORT, HW_I2C1_SCL_PIN, HW_I2C1_SDA_PORT, HW_I2C1_SDA_PIN, 0, 0) \
	X(API_I2C2, HW_I2C2_SCL_PORT, HW_I2C2_SCL_PIN, HW_I2C2_SDA_PORT, HW_I2C2_SDA_PIN, 0, 0) \
	X(API_I2C3, HW_I2C3_SCL_PORT, HW_I2C3_SCL_PIN, HW_I2C3_SDA_PORT, HW_I2C3_SDA_PIN, 0, 0) \
	X(API_I2C4, HW_I2C4_SCL_PORT, HW_I2C4_SCL_PIN, HW_I2C4_SDA_PORT, HW_I2C4_SDA_PIN, 0, 0)


/* 软件 SPI2 引脚定义：给 NRF24L01 */
#define HW_SPI2_SCK_PORT  GPIOA
#define HW_SPI2_SCK_PIN   GPIO_Pin_15

#define HW_SPI2_MOSI_PORT GPIOD
#define HW_SPI2_MOSI_PIN  GPIO_Pin_5

#define HW_SPI2_MISO_PORT GPIOD
#define HW_SPI2_MISO_PIN  GPIO_Pin_1

#define HW_SPI2_CS_PORT   GPIOD
#define HW_SPI2_CS_PIN    GPIO_Pin_7

/* SPI 板级映射：SPI2 给 NRF24L01（SPI1 已随 7 针 OLED 弃用） */
#define HW_SPI_MAP(X) \
	X(API_SPI2, HW_SPI2_CS_PORT, HW_SPI2_CS_PIN, \
	  HW_SPI2_SCK_PORT, HW_SPI2_SCK_PIN, \
	  HW_SPI2_MOSI_PORT, HW_SPI2_MOSI_PIN, \
	  HW_SPI2_MISO_PORT, HW_SPI2_MISO_PIN, 0, 0, 0, 0)

/* OLED SPI 控制引脚定义：DC=PB15，RES=PB14 */
#define HW_OLED_DC_PORT GPIOB
#define HW_OLED_DC_PIN  GPIO_Pin_15
#define HW_OLED_RES_PORT GPIOB
#define HW_OLED_RES_PIN  GPIO_Pin_14

/* OLED SPI 控制引脚映射：注册 1 组 DC/RES */
#define HW_OLED_SPI_CTRL_MAP(X) \
	X(HW_OLED_DC_PORT, HW_OLED_DC_PIN, HW_OLED_RES_PORT, HW_OLED_RES_PIN)

/* NRF24L01 控制引脚定义：CE=PC6 */
#define HW_NRF24L01_CE_PORT GPIOC
#define HW_NRF24L01_CE_PIN  GPIO_Pin_6

/* NRF24L01 控制引脚映射：注册 1 组 CE */
#define HW_NRF24L01_CTRL_MAP(X) \
	X(HW_NRF24L01_CE_PORT, HW_NRF24L01_CE_PIN)

/* HC-SR04 超声波引脚定义：Trig=PA4（触发输出），Echo=PA6（回波输入） */
#define HW_HCSR04_TRIG_PORT GPIOA
#define HW_HCSR04_TRIG_PIN  GPIO_Pin_4
#define HW_HCSR04_ECHO_PORT GPIOA
#define HW_HCSR04_ECHO_PIN  GPIO_Pin_6

/* HC-SR04 板级映射：当前注册 1 个超声波 */
#define HW_HCSR04_MAP(X) \
    X(HCSR04_1, HW_HCSR04_TRIG_PORT, HW_HCSR04_TRIG_PIN, HW_HCSR04_ECHO_PORT, HW_HCSR04_ECHO_PIN)

/* 当前板子上注册了 4 个 LED */
#define HW_LED_COUNT  4U
/* 当前板子上注册了 2 个按键 */
#define HW_KEY_COUNT  2U
/* 当前板子上注册了 3 路 USART */
#define HW_USART_COUNT  4U
/* 当前板子上注册了 1 路 TIM */
#define HW_TIM_COUNT  3U
/* 当前板子上注册了 4 路 PWM 通道 */
#define HW_PWM_COUNT  4U
/* 当前板子上注册了 4 路 ADC 通道 */
#define HW_ADC_COUNT  1U
/* 当前板子上注册了 4 路软件 I2C */
#define HW_I2C_COUNT  4U
/* 当前板子上注册了 2 路软件 SPI */
#define HW_SPI_COUNT  1U
/* 当前板子上注册了 1 组 OLED SPI 控制引脚 */
#define HW_OLED_SPI_CTRL_COUNT  1U
/* 当前板子上注册了 1 组 NRF24L01 控制引脚 */
#define HW_NRF24L01_CTRL_COUNT  1U
/* 当前板子上注册了 1 个 HC-SR04 超声波 */
#define HW_HCSR04_COUNT   1U

#endif /* __407_HW_CONFIG_H */
